#!/usr/bin/env groovy

library identifier: 'jenkins-shared-library@main', retriever: modernSCM(
        [$class: 'GitSCMSource',
         remote: 'git@github.com:andyt98/jenkins-shared-library.git',
         credentialsId: '6006db77-237c-41a0-973d-58072df7d2d9'
        ]
)


def gv

pipeline {
    agent any
    tools {
        maven 'maven-3.6.3'
    }
    stages {
        stage("init") {
            steps {
                script {
                    gv = load "script.groovy"
                }
            }
        }
        stage("build jar") {
            steps {
                script {
                    buildJar()
                }
            }
        }
        stage("build and push image") {
            steps {
                script {
                    buildImage 'andyt98/demo-app:1.3'
                    dockerLogin()
                    dockerPush 'andyt98/demo-app:1.3'
                }
            }
        }
        stage("deploy") {
            steps {
                script {
                    gv.deployApp()
                }
            }
        }
    }
}

