apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deploynent
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: quay.io/ioan_stan1/django-sample-docker-training
        ports:
        - containerPort: 8000
        env:
        - name: DB_LOCALDB
          value: "False"
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: LoadBalancer
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
