- name: Time Synchronization Play
  hosts: servers
  vars:
    timesync_ntp_servers:
      - hostname: 0.rhel.pool.ntp.org
        iburst: true
      - hostname: 1.rhel.pool.ntp.org
        iburst: true
      - hostname: 2.rhel.pool.ntp.org
        iburst: true
    timezone: UTC

  roles:
    - /usr/share/ansible/roles/rhel-system-roles.timesync

  post_tasks:
    - name: Set timezone
      community.general.timezone:
        name: "{{ timezone }}"
      notify: Reboot host

  handlers:
    - name: Reboot host
      ansible.builtin.reboot:
